In [2]:
from sklearn.metrics import accuracy_score,classification_report,f1_score
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv("novagen_dataset.csv")
df

       Age   BMI  Blood_Pressure  Cholesterol  ...  Diet_Type__Vegetarian  Blood_Group_AB  Blood_Group_B  Blood_Group_O
0      2.0  26.0           111.0        198.0  ...                   True            True          False          False
1      8.0  24.0           121.0        199.0  ...                  False            True          False          False
2     81.0  27.0           147.0        203.0  ...                  False           False          False          False
3     25.0  21.0           150.0        199.0  ...                  False           False           True          False
4     24.0  26.0           146.0        202.0  ...                   True           False           True          False
...    ...   ...             ...          ...  ...                    ...             ...            ...            ...
9544   5.0  22.0           109.0        203.0  ...                  False            True          False          False
9545  94.0  26.0           144.0        203.0  ...                   True           False           True          False
9546  10.0  23.0           185.0        198.0  ...                  False            True          False          False
9547  50.0  29.0           166.0        200.0  ...                  False            True          False          False
9548  69.0  29.0           178.0        203.0  ...                  False            True          False          False

[9549 rows x 23 columns]

In [4]:
df

       Age   BMI  Blood_Pressure  Cholesterol  ...  Diet_Type__Vegetarian  Blood_Group_AB  Blood_Group_B  Blood_Group_O
0      2.0  26.0           111.0        198.0  ...                   True            True          False          False
1      8.0  24.0           121.0        199.0  ...                  False            True          False          False
2     81.0  27.0           147.0        203.0  ...                  False           False          False          False
3     25.0  21.0           150.0        199.0  ...                  False           False           True          False
4     24.0  26.0           146.0        202.0  ...                   True           False           True          False
...    ...   ...             ...          ...  ...                    ...             ...            ...            ...
9544   5.0  22.0           109.0        203.0  ...                  False            True          False          False
9545  94.0  26.0           144.0        203.0  ...                   True           False           True          False
9546  10.0  23.0           185.0        198.0  ...                  False            True          False          False
9547  50.0  29.0           166.0        200.0  ...                  False            True          False          False
9548  69.0  29.0           178.0        203.0  ...                  False            True          False          False

[9549 rows x 23 columns]

In [5]:
X = df.drop("Target",axis = 1)
y= df["Target"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42,stratify=y
)

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
lr = LogisticRegression(
    penalty="l1",
    solver = "liblinear",
    max_iter=1000
)
lr.fit(X_train_scaled,y_train)
y_pred = lr.predict(X_test_scaled)

print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("CR :",classification_report(y_test,y_pred))

Accuracy Score :  0.8141361256544503
CR :               precision    recall  f1-score   support

           0       0.81      0.80      0.80       914
           1       0.82      0.83      0.82       996

    accuracy                           0.81      1910
   macro avg       0.81      0.81      0.81      1910
weighted avg       0.81      0.81      0.81      1910

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [12]:
knn = KNeighborsClassifier(
    n_neighbors=5
)
knn.fit(X_train_scaled,y_train)
y_pred = knn.predict(X_test_scaled)
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("F1 Score : ",f1_score(y_test,y_pred))
print("CR : ",classification_report(y_test,y_pred))

Accuracy Score :  0.8832460732984293
F1 Score :  0.8875441250630358
CR :                precision    recall  f1-score   support

           0       0.87      0.88      0.88       914
           1       0.89      0.88      0.89       996

    accuracy                           0.88      1910
   macro avg       0.88      0.88      0.88      1910
weighted avg       0.88      0.88      0.88      1910

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(
    n_estimators=201,
    max_depth=None,
    random_state = 42
)
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("F1 Score : ",f1_score(y_test,y_pred))
print("CR : ",classification_report(y_test,y_pred))

Accuracy Score :  0.9392670157068063
F1 Score :  0.9428571428571428
CR :                precision    recall  f1-score   support

           0       0.96      0.92      0.94       914
           1       0.93      0.96      0.94       996

    accuracy                           0.94      1910
   macro avg       0.94      0.94      0.94      1910
weighted avg       0.94      0.94      0.94      1910

In [22]:
from sklearn.ensemble import GradientBoostingClassifier

In [26]:
gd = GradientBoostingClassifier(
    n_estimators = 151,
    learning_rate=0.1,
    max_depth=3,
    random_state = 42
)

In [28]:
gd.fit(X_train,y_train)
y_pred = gd.predict(X_test)
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("F1 Score : ",f1_score(y_test,y_pred))
print("CR : ",classification_report(y_test,y_pred))

Accuracy Score :  0.9303664921465968
F1 Score :  0.934320987654321
CR :                precision    recall  f1-score   support

           0       0.94      0.91      0.93       914
           1       0.92      0.95      0.93       996

    accuracy                           0.93      1910
   macro avg       0.93      0.93      0.93      1910
weighted avg       0.93      0.93      0.93      1910

In [29]:
from sklearn.ensemble import VotingClassifier

In [30]:
vc = VotingClassifier(
    [
        ("lr",lr),
        ("knn",knn),
        ("rf",rf)
    ],
    voting="soft"
)
vc.fit(X_train,y_train)
y_pred = vc.predict(X_test)
print("Accuracy Score : ",accuracy_score(y_test,y_pred))
print("F1 Score : ",f1_score(y_test,y_pred))
print("CR : ",classification_report(y_test,y_pred))

Accuracy Score :  0.9109947643979057
F1 Score :  0.915506958250497
CR :                precision    recall  f1-score   support

           0       0.92      0.90      0.91       914
           1       0.91      0.92      0.92       996

    accuracy                           0.91      1910
   macro avg       0.91      0.91      0.91      1910
weighted avg       0.91      0.91      0.91      1910